spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/linkedinaddon
    username: ${DB_USER:postgres}
    password: ${DB_PASS:stePAOL!?}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect  

  application:
    name: linkedin-addon

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
    org.springframework.boot.autoconfigure: DEBUG

server:
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: ALWAYS
